### ISSUE TITLE
Android > Extrinsic > Msa > deleteMsaPublicKey

### ISSUE THREAD

**Issue by DannyAhmedApex** [LibertyDSNP/dsnp-wallet-kotlin#97]
![image](https://github.com/LibertyDSNP/dsnp-wallet-kotlin/assets/108344795/43005ba7-30e7-4c04-84c1-6ce831dbd5d6)

**Comment by VitaliKrasnik** [comment]
Danny, could you please check why is the application crashing when the user clicks on the 
'The Frequency Chain Test'

`2023-07-08 07:29:33.673 13240-13240 AndroidRuntime          com...nished.dsnp_wallet_kotlin.dev  E  FATAL EXCEPTION: main
                                                                                                    Process: com.unfinished.dsnp_wallet_kotlin.dev, PID: 13240
                                                                                                    java.util.NoSuchElementException: Key 496e2f8a93bf4576317f998d01480f9068014b368856ec088a63e57071cd1d49 is missing in the map.
                                                                                                    	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
                                                                                                    	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:349)
                                                                                                    	at io.novafoundation.nova.runtime.multiNetwork.connection.ConnectionPool.getConnection(ConnectionPool.kt:10)
                                                                                                    	at io.novafoundation.nova.runtime.multiNetwork.ChainRegistry.getConnection(ChainRegistry.kt:90)
                                                                                                    	at io.novafoundation.nova.runtime.network.rpc.RpcCalls.socketFor(RpcCalls.kt:144)
                                                                                                    	at io.novafoundation.nova.runtime.network.rpc.RpcCalls.getBlockHash(RpcCalls.kt:141)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestViewModel$getGesisHashFromBlockHash$1.invokeSuspend(TestViewModel.kt:129)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:365)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestViewModel.getGesisHashFromBlockHash(TestViewModel.kt:128)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestViewModel.<init>(TestViewModel.kt:110)
                                                                                                    	at com.unfinished.dsnp_wallet_kotlin.DaggerMyApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerMyApplication_HiltComponents_SingletonC.java:1173)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:101)
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:90)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestFragment.getViewModel(TestFragment.kt:37)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestFragment.updateAdapters(TestFragment.kt:478)
                                                                                                    	at com.unfinished.feature_account.presentation.test.TestFragment.initViews(TestFragment.kt:50)
                                                                                                    	at io.novafoundation.nova.common.base.BaseFragmentDelegate.onViewCreated(BaseFragmentMixin.kt:94)
                                                                                                    	at io.novafoundation.nova.common.base.BaseFragment.onViewCreated(BaseFragment.kt:19)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
                                                                                                    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
2023-07-08 07:29:33.674 13240-13240 AndroidRuntime          com...nished.dsnp_wallet_kotlin.dev  E  	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
                                                                                                    	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.unfinished.dsnp_wallet_kotlin.databinding.TestScreenBinding.inflate(TestScreenBinding.java:42)
                                                                                                    	at com.unfinished.dsnp_wallet_kotlin.ui.test.TestScreenKt$TestScreen$1.invoke(TestScreen.kt:14)
                                                                                                    	at com.unfinished.dsnp_wallet_kotlin.ui.test.TestScreenKt$TestScreen$1.invoke(TestScreen.kt:14)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewBindingKt$AndroidViewBinding$viewBlock$1$1.invoke(AndroidViewBinding.kt:83)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewBindingKt$AndroidViewBinding$viewBlock$1$1.invoke(AndroidViewBinding.kt:79)
                                                                                                    	at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:314)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:247)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:246)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(Composables.kt:254)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1615)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1613)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3575)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3572)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:810)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:842)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:592)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@893fb75, Dispatchers.Main.immediate]
2023-07-08 07:29:33.676   566-579   ActivityTaskManager     system_server                        W    Force finishing activity com.unfinished.dsnp_wallet_kotlin.dev/com.unfinished.dsnp_wallet_kotlin.MainActivity
2023-07-08 07:29:33.684 13240-13240 Process                 com...nished.dsnp_wallet_kotlin.dev  I  Sending signal. PID: 13240 SIG: 9
2023-07-08 07:29:33.714   566-3216  WindowManager           system_server                        I  WIN DEATH: Window{63b1dc7 u0 com.unfinished.dsnp_wallet_kotlin.dev/com.unfinished.dsnp_wallet_kotlin.MainActivity}
2023-07-08 07:29:33.714   566-3216  InputManager-JNI        system_server                        W  Input channel object '63b1dc7 com.unfinished.dsnp_wallet_kotlin.dev/com.unfinished.dsnp_wallet_kotlin.MainActivity (client)' was disposed without first being removed with the input manager!
2023-07-08 07:29:33.714   566-3482  ActivityManager         system_server                        I  Process com.unfinished.dsnp_wallet_kotlin.dev (pid 13240) has died: fg  TOP 
2023-07-08 07:29:34.177   566-584   ActivityTaskManager     system_server                        W  Activity top resumed state loss timeout for ActivityRecord{13f9fe7 u0 com.unfinished.dsnp_wallet_kotlin.dev/com.unfinished.dsnp_wallet_kotlin.MainActivity t-1 f}}
`
